# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: 
- master
pr:
- master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Run_and_publish_unit_tests
    jobs:
      - job:
        steps:
          - task: Bash@3
            displayName: Installing TFX
            inputs:
              targetType: inline
              script: |
                npm install -g tfx-cli
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: 'bbplugin' 
          - task: Bash@3
            displayName: Compile Javascript
            inputs:
              targetType: "inline"
              script: |
                cd bbplugin
                tsc
          - task: Bash@3
            displayName: Create artifact
            inputs:
              targetType: "inline"
              script: |
                npx tfx-cli extension create
                versionString=$(node -p "require('./vss-extension.json').version")
                echo "##vso[build.updatebuildnumber]$versionString"
          - task: CopyFiles@2
            inputs:
              contents: 'pablotoledo.bitbucket-commit-status-$(build.updatebuildnumber).vsix'
              targetFolder: ./publish
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: ./publish
              artifactName: pablotoledo.bitbucket-commit-status-$(build.updatebuildnumber)